name: release

on:
  # pull_request:
  #   paths:
  #     - .github/workflows/release.yml
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name for release"
        required: true



jobs:
  release-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Update rust
        run: rustup update

      - name: Compress
        shell: pwsh
        run: |
          cargo build --release
          Compress-Archive ./target/release/flow.exe ./flow-windows.zip

      - uses: actions/upload-artifact@v3
        with:
          name: flow-windows
          path: ./flow-windows.zip
          retention-days: 1

  release-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Update rust
        run: rustup update

      - name: Compress
        run: |
          cargo build --release
          tar -czf ./flow-linux.tar.gz ./target/release/flow

      - uses: actions/upload-artifact@v3
        with:
          name: flow-linux
          path: ./flow-linux.tar.gz
          retention-days: 1

  release-macos:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      
      - name: Update rust
        run: rustup update

      - name: Compress
        run: |
          cargo build --release
          zip -r ./flow-macos.zip ./target/release/flow

      - uses: actions/upload-artifact@v3
        with:
          name: flow-macos
          path: ./flow-macos.zip
          retention-days: 1
      
  publish:
    needs: [release-windows,release-linux,release-macos]
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      GH_TOKEN : ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3

      - name: Show downloads
        run: ls 

      - name: Publish binaries
      # Delete --draft
        run: |
          gh release create ${{inputs.tag_name}} --title "${{inputs.tag_name}}" --draft  flow-macos/* flow-linux/* flow-windows/*
